### PR TITLE
allow to specify the `message` as function.

### PR DESCRIPTION
**Pull request by kangguru**
like `min` and `max` so the resulting message can reference model attributes.

``` javascript
    @validatesRangeOf 'amount',
                      max: 10,
                      message: (( resource ) -> @get('max_amount'))
```

### CODE REVIEW

**Comment by lucaong** [comment]
I like this, very useful! I would like to have this behavior on all validators though. It would need a little code refactoring, but we can get one DaWanda developer to do this.

**Comment by kangguru** [comment]
:tada: agree that this is something all validators can benefit from. although i didn't wanted to add it to all before knowing if you think it is useful :)

**Comment by lucaong** [comment]
In case we need it now, we could merge this and then add it to all validators ;)

**Comment by kangguru** [comment]
✓ i've done it

**Comment by kangguru** [comment]
@lucaong so we'll merge it? ;)

**Comment by lucaong** [comment]
:+1: yes

**Comment by kangguru** [comment]
u r awesome

**Pull request merged**
